
export const ADD_QUESTIONS="ADDQUESTIONS"
export const GET_QUESTIONS="GETQUESTIONS"
export const DELETE_QUESTIONS="DELETEQUESTIONS"
export const UPDATE_QUESTIONS="UPDATEQUESTIONS"

export const ADD_QUESTIONS_RED = "ADDQUESTIONSRED"
export const GET_QUESTIONS_RED="GETQUESTIONSRED"
export const DELETE_QUESTIONS_RED="DELETEQUESTIONSRED"
export const UPDATE_QUESTIONS_RED="UPDATEQUESTIONSRED"