
export const ADD_QUESTIONS="ADDQUESTIONS"
export const GET_QUESTIONS="GETQUESTIONS"
export const GET_EXAM_QUESTIONS="GETEXAMQUESTIONS"
export const DELETE_QUESTIONS="DELETEQUESTIONS"
export const UPDATE_QUESTIONS="UPDATEQUESTIONS"

export const ADD_QUESTIONS_RED = "ADDQUESTIONSRED"
export const GET_QUESTIONS_RED="GETQUESTIONSRED"
export const GET_EXAM_QUESTIONS_RED="GETEXAMQUESTIONSRED"
export const DELETE_QUESTIONS_RED="DELETEQUESTIONSRED"
export const UPDATE_QUESTIONS_RED="UPDATEQUESTIONSRED"

export const ADD_EXAMS="ADDEXAMS"
export const GET_EXAMS="GETEXAMS"
export const DELETE_EXAMS="DELETEEXAMS"
export const UPDATE_EXAMS="UPDATEEXAMS"

export const ADD_EXAMS_RED = "ADDEXAMSRED"
export const GET_EXAMS_RED="GETEXAMSRED"
export const DELETE_EXAMS_RED = "DELETEEXAMSRED"
export const UPDATE_EXAMS_RED = "UPDATEEXAMSRED"

export const ADD_USERS="ADDUSERS"
export const GET_USERS="GETUSERS"
export const DELETE_USERS="DELETEUSERS"
export const UPDATE_USERS="UPDATEUSERS"

export const ADD_USERS_RED = "ADD USERSRED"
export const GET_USERS_RED="GEUSERSRED"
export const DELETE_USERS_RED="DELETEUSERSRED"
export const UPDATE_USERS_RED="UPDATEUSERSRED"